using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using DeltaSharp.Types;
using Xunit;

namespace DeltaSharp.Core.Tests.Types;

/// <summary>
/// #679: property-level pins on the single consolidated schema serializer
/// (<c>DeltaSharp.Abstractions.SchemaJson</c>), which since the consolidation is the sole producer of
/// BOTH the Delta log <c>metaData.schemaString</c> and the Parquet footer schema string. Because those
/// two strings are now generated by one implementation, no differential test between them can detect a
/// serializer defect any more — so the serializer needs properties pinned against itself.
/// </summary>
/// <remarks>
/// Hosted in <c>DeltaSharp.Core.Tests</c> rather than the Storage suite deliberately: this project
/// multi-targets <c>net8.0;net10.0</c>, so these run on BOTH TFMs, whereas the Storage suite is
/// net10.0-only. The serializer emits doubles via <c>double.ToString("R")</c> and parses numbers via
/// <c>TryGetInt64</c>/<c>GetDouble</c>, all of which are runtime-version-sensitive, so net8.0 coverage
/// is worth real money here.
/// </remarks>
public sealed class SchemaJsonSerializerPropertyTests
{
    // A corpus spanning the recursion base (every atomic + decimal), every complex constructor
    // (array/map/struct), both nullability polarities, empty struct, deep nesting, and typed metadata
    // at nested depth — i.e. every arm of WriteType and WriteMetadataValue.
    public static TheoryData<string, DataType> Corpus()
    {
        var data = new TheoryData<string, DataType>();

        var atomics = new (string Name, DataType Type)[]
        {
            ("boolean", DataTypes.BooleanType),
            ("byte", DataTypes.ByteType),
            ("short", DataTypes.ShortType),
            ("integer", DataTypes.IntegerType),
            ("long", DataTypes.LongType),
            ("float", DataTypes.FloatType),
            ("double", DataTypes.DoubleType),
            ("string", DataTypes.StringType),
            ("binary", DataTypes.BinaryType),
            ("date", DataTypes.DateType),
            ("timestamp", DataTypes.TimestampType),
            ("timestamp_ntz", DataTypes.TimestampNtzType),
        };

        foreach ((string name, DataType type) in atomics)
        {
            data.Add(name, type);
        }

        // Decimal boundaries: precision/scale extremes carry the parameterized TypeName.
        data.Add("decimal-min", DataTypes.CreateDecimalType(1, 0));
        data.Add("decimal-max", DataTypes.CreateDecimalType(38, 38));
        data.Add("decimal-mixed", DataTypes.CreateDecimalType(20, 4));

        data.Add("array-nullable", DataTypes.CreateArrayType(DataTypes.StringType, containsNull: true));
        data.Add("array-non-nullable", DataTypes.CreateArrayType(DataTypes.LongType, containsNull: false));
        data.Add("map-nullable", DataTypes.CreateMapType(DataTypes.StringType, DataTypes.LongType, valueContainsNull: true));
        data.Add("map-non-nullable", DataTypes.CreateMapType(DataTypes.StringType, DataTypes.LongType, valueContainsNull: false));
        data.Add("empty-struct", StructType.Empty);

        var leaf = new StructType(new[]
        {
            new StructField("x", DataTypes.LongType, nullable: false),
            new StructField("y", DataTypes.CreateDecimalType(10, 2), nullable: true),
        });
        data.Add("struct", leaf);
        data.Add("array-of-struct", DataTypes.CreateArrayType(leaf, containsNull: true));
        data.Add("map-struct-key", DataTypes.CreateMapType(leaf, DataTypes.StringType, valueContainsNull: false));
        data.Add("map-struct-value", DataTypes.CreateMapType(DataTypes.StringType, leaf, valueContainsNull: true));

        // Depth-4 alternation of every complex constructor.
        DataType deep = DataTypes.CreateArrayType(
            DataTypes.CreateMapType(
                DataTypes.StringType,
                DataTypes.CreateArrayType(leaf, containsNull: false),
                valueContainsNull: true),
            containsNull: false);
        data.Add("deep-nest", deep);

        // Model-derived metadata corpus: every MetadataValueKind must be represented directly from the enum,
        // so adding a new kind cannot leave Core's schema serializer corpus silently incomplete on net8.0.
        var metadataEntries = new List<KeyValuePair<string, MetadataValue>>
        {
            new("delta.columnMapping.id", MetadataValue.Long(9)),
        };
        foreach (MetadataValueKind kind in Enum.GetValues<MetadataValueKind>())
        {
            metadataEntries.Add(new KeyValuePair<string, MetadataValue>(
                string.Create(CultureInfo.InvariantCulture, $"m.{kind}"),
                ValueOfKind(kind)));
        }

        var metadata = FieldMetadata.FromValues(metadataEntries);
        data.Add("metadata-rich", new StructType(new[]
        {
            new StructField("mapped", DataTypes.CreateArrayType(leaf, containsNull: true), nullable: true, metadata),
        }));

        // Names needing JSON escaping, for the round-trip theories below. NOTE: those theories assert
        // idempotence and structural equality, BOTH of which are invariant under the encoder choice —
        // so this entry does NOT pin the escaped bytes. That is done explicitly by
        // JsonEscapingPolicy_IsPinned_SoTheEncoderCannotSilentlyChangePersistedBytes.
        data.Add("escaped-names", new StructType(new[]
        {
            new StructField("quote\"name", DataTypes.StringType, nullable: true),
            new StructField("back\\slash", DataTypes.StringType, nullable: true),
            new StructField("unicode-\u00e9\u4e2d", DataTypes.StringType, nullable: true),
        }));

        return data;
    }

    private static MetadataValue ValueOfKind(MetadataValueKind kind) => kind switch
    {
        MetadataValueKind.Null => MetadataValue.Null,
        MetadataValueKind.String => MetadataValue.String("v"),
        MetadataValueKind.Long => MetadataValue.Long(42),
        MetadataValueKind.Double => MetadataValue.Double(4.0), // integral double must stay Double
        MetadataValueKind.Boolean => MetadataValue.Boolean(true),
        MetadataValueKind.Array => MetadataValue.Array(new[] { MetadataValue.Long(1), MetadataValue.String("x") }),
        MetadataValueKind.Nested => MetadataValue.Nested(FieldMetadata.FromValues(new[]
        {
            new KeyValuePair<string, MetadataValue>("deep", MetadataValue.String("v")),
        })),
        _ => throw new NotSupportedException(
            $"MetadataValueKind.{kind} was added but this corpus does not build one."),
    };

    [Theory]
    [MemberData(nameof(Corpus))]
    public void SerializeParseSerialize_IsIdempotent(string name, DataType type)
    {
        // The core property: serializer and parser are mutually consistent, so a schemaString written
        // today re-reads to a type tree that re-serializes to identical bytes. A Delta schemaString is
        // persistent and cross-engine-visible, so a non-idempotent round trip would be retroactively
        // unfixable once committed to a log.
        string once = SchemaJson.ToJson(type);
        DataType parsed = SchemaJson.FromJson(once);
        string twice = SchemaJson.ToJson(parsed);

        Assert.Equal(once, twice);
        Assert.False(string.IsNullOrEmpty(once), $"corpus entry '{name}' serialized to nothing");
    }

    [Theory]
    [MemberData(nameof(Corpus))]
    public void ParsedTree_IsStructurallyEqualToTheOriginal(string name, DataType type)
    {
        // Idempotence alone would tolerate a serializer that discards a field on BOTH passes. Pin the
        // parsed tree against the original so information loss is caught too.
        DataType parsed = SchemaJson.FromJson(SchemaJson.ToJson(type));

        Assert.Equal(type, parsed);
        Assert.Equal(type.TypeName, parsed.TypeName);
        Assert.Equal(type.SimpleString, parsed.SimpleString);
        Assert.True(type.Equals(parsed), $"corpus entry '{name}' did not round-trip structurally");
    }

    [Fact]
    public void EveryAtomicType_SerializesToItsPinnedProtocolName()
    {
        // The Delta protocol fixes these spellings; they are not ours to change. Pinning them literally
        // is what catches a corrupted shared default arm (e.g. TypeName uppercased), which no
        // footer-vs-log comparison can see now that a single serializer feeds both.
        var expected = new (DataType Type, string Json)[]
        {
            (DataTypes.BooleanType, "\"boolean\""),
            (DataTypes.ByteType, "\"byte\""),
            (DataTypes.ShortType, "\"short\""),
            (DataTypes.IntegerType, "\"integer\""),
            (DataTypes.LongType, "\"long\""),
            (DataTypes.FloatType, "\"float\""),
            (DataTypes.DoubleType, "\"double\""),
            (DataTypes.StringType, "\"string\""),
            (DataTypes.BinaryType, "\"binary\""),
            (DataTypes.DateType, "\"date\""),
            (DataTypes.TimestampType, "\"timestamp\""),
            (DataTypes.TimestampNtzType, "\"timestamp_ntz\""),
            (DataTypes.CreateDecimalType(38, 18), "\"decimal(38,18)\""),
            (DataTypes.CreateDecimalType(1, 0), "\"decimal(1,0)\""),
        };

        foreach ((DataType type, string json) in expected)
        {
            Assert.Equal(json, SchemaJson.ToJson(type));
        }
    }

    [Fact]
    public void ComplexTypes_SerializeToTheirPinnedProtocolShape()
    {
        // Field ORDER inside array/map/struct objects is part of the pinned wire shape, so a reordering
        // regression (e.g. emitting containsNull before elementType) fails here.
        Assert.Equal(
            "{\"type\":\"array\",\"elementType\":\"string\",\"containsNull\":true}",
            SchemaJson.ToJson(DataTypes.CreateArrayType(DataTypes.StringType, containsNull: true)));

        Assert.Equal(
            "{\"type\":\"map\",\"keyType\":\"string\",\"valueType\":\"long\",\"valueContainsNull\":false}",
            SchemaJson.ToJson(DataTypes.CreateMapType(DataTypes.StringType, DataTypes.LongType, valueContainsNull: false)));

        Assert.Equal(
            "{\"type\":\"struct\",\"fields\":[]}",
            SchemaJson.ToJson(StructType.Empty));

        Assert.Equal(
            "{\"type\":\"struct\",\"fields\":[{\"name\":\"f\",\"type\":\"long\",\"nullable\":true,\"metadata\":{}}]}",
            SchemaJson.ToJson(new StructType(new[] { new StructField("f", DataTypes.LongType, nullable: true) })));
    }

    [Fact]
    public void JsonEscapingPolicy_IsPinned_SoTheEncoderCannotSilentlyChangePersistedBytes()
    {
        // The Utf8JsonWriter's JavaScriptEncoder is part of the persisted wire format, not an
        // implementation detail: switching to JavaScriptEncoder.UnsafeRelaxedJsonEscaping emits the SAME
        // logical schema with DIFFERENT bytes for any non-ASCII or quoted field name, changing the
        // on-disk metaData.schemaString of a committed table. Nothing else in the suite pins it —
        // round-trip idempotence and structural equality are both invariant under encoder choice — so
        // these literals are the only thing standing between a one-word constructor change and a silent
        // change to every schemaString carrying a non-ASCII column name.
        //
        // Default (strict) encoder policy, pinned exactly: non-ASCII escapes to \uXXXX with UPPERCASE
        // hex, and a double quote escapes to \u0022 rather than \". UnsafeRelaxedJsonEscaping emits the
        // literal UTF-8 character and \" respectively, so each assertion below fails under it.
        Assert.Equal(
            "{\"type\":\"struct\",\"fields\":[{\"name\":\"caf\\u00E9\",\"type\":\"string\"" +
            ",\"nullable\":true,\"metadata\":{}}]}",
            SchemaJson.ToJson(new StructType(new[]
            {
                new StructField("caf\u00e9", DataTypes.StringType, nullable: true),
            })));

        // A non-BMP-adjacent CJK code point, to pin that the escape is per-code-point uppercase hex.
        Assert.Equal(
            "{\"type\":\"struct\",\"fields\":[{\"name\":\"a\\u4E2Db\",\"type\":\"string\"" +
            ",\"nullable\":true,\"metadata\":{}}]}",
            SchemaJson.ToJson(new StructType(new[]
            {
                new StructField("a\u4e2db", DataTypes.StringType, nullable: true),
            })));

        // The quote case discriminates the two encoders most sharply: \u0022 (strict) vs \" (relaxed).
        Assert.Equal(
            "{\"type\":\"struct\",\"fields\":[{\"name\":\"q\\u0022z\",\"type\":\"string\"" +
            ",\"nullable\":true,\"metadata\":{}}]}",
            SchemaJson.ToJson(new StructType(new[]
            {
                new StructField("q\"z", DataTypes.StringType, nullable: true),
            })));

        // Metadata KEYS and string VALUES go through the same encoder, so pin them too — column-mapping
        // physical names are attacker-adjacent free text and are exactly where a non-ASCII name lands.
        Assert.Equal(
            "{\"type\":\"struct\",\"fields\":[{\"name\":\"f\",\"type\":\"long\"" +
            ",\"nullable\":true,\"metadata\":{\"k\\u00E9y\":\"v\\u00E9l\"}}]}",
            SchemaJson.ToJson(new StructType(new[]
            {
                new StructField("f", DataTypes.LongType, nullable: true, FieldMetadata.FromValues(new[]
                {
                    new KeyValuePair<string, MetadataValue>("k\u00e9y", MetadataValue.String("v\u00e9l")),
                })),
            })));
    }

    [Fact]
    public void IntegralDouble_KeepsAFractionalPart_SoItReReadsAsDouble()
    {
        // #330 interop contract: an integral Double must not collapse to a bare integer literal, or a
        // reader re-types it as Long. Asserted on the emitted bytes AND on the re-read kind.
        var schema = new StructType(new[]
        {
            new StructField("f", DataTypes.LongType, nullable: true, FieldMetadata.FromValues(new[]
            {
                new KeyValuePair<string, MetadataValue>("d", MetadataValue.Double(5.0)),
                new KeyValuePair<string, MetadataValue>("l", MetadataValue.Long(5)),
            })),
        });

        string json = SchemaJson.ToJson(schema);
        Assert.Contains("\"d\":5.0", json, StringComparison.Ordinal);
        Assert.Contains("\"l\":5", json, StringComparison.Ordinal);

        var parsed = (StructType)SchemaJson.FromJson(json);
        FieldMetadata metadata = parsed["f"].Metadata;
        Assert.True(metadata.TryGetValue("d", out MetadataValue? d));
        Assert.True(metadata.TryGetValue("l", out MetadataValue? l));
        Assert.Equal(MetadataValueKind.Double, d!.Kind);
        Assert.Equal(MetadataValueKind.Long, l!.Kind);
    }

    [Fact]
    public void FieldMetadata_SerializesInKeySortedOrder_SoOutputIsDeterministic()
    {
        // The schemaString is diffed across commits and compared by downstream consumers, so insertion
        // order must never leak into the bytes.
        var forward = new StructType(new[]
        {
            new StructField("f", DataTypes.LongType, nullable: true, FieldMetadata.FromValues(new[]
            {
                new KeyValuePair<string, MetadataValue>("a", MetadataValue.Long(1)),
                new KeyValuePair<string, MetadataValue>("b", MetadataValue.Long(2)),
                new KeyValuePair<string, MetadataValue>("c", MetadataValue.Long(3)),
            })),
        });
        var reversed = new StructType(new[]
        {
            new StructField("f", DataTypes.LongType, nullable: true, FieldMetadata.FromValues(new[]
            {
                new KeyValuePair<string, MetadataValue>("c", MetadataValue.Long(3)),
                new KeyValuePair<string, MetadataValue>("b", MetadataValue.Long(2)),
                new KeyValuePair<string, MetadataValue>("a", MetadataValue.Long(1)),
            })),
        });

        Assert.Equal(SchemaJson.ToJson(forward), SchemaJson.ToJson(reversed));
        Assert.Contains("\"metadata\":{\"a\":1,\"b\":2,\"c\":3}", SchemaJson.ToJson(forward), StringComparison.Ordinal);
    }

    [Fact]
    public void Corpus_ProducesDistinctStringsPerShape()
    {
        // Guards the corpus itself: if a future edit made two entries collide, the theories above would
        // silently lose coverage while still passing.
        string[] serialized = Corpus()
            .Select(row => SchemaJson.ToJson((DataType)row[1]!))
            .ToArray();

        Assert.Equal(serialized.Length, serialized.Distinct(StringComparer.Ordinal).Count());
    }

    // #709: a byte-literal pin over a double needing MORE than 15 significant digits, so a regression that
    // truncated the persisted rendering (e.g. "R" -> "G15", or any precision-losing format specifier) fails
    // the suite. Every other double pinned in the repo is <= 15 significant digits, so "R" and a 15-digit
    // "G" render identically for all of them and none of them can catch this drift.
    //
    // metaData.schemaString is persistent, cross-engine-visible, and retroactively unfixable once committed,
    // so silent drift here is permanent. On modern .NET "R", "G", and the dropped-specifier default all emit
    // the shortest round-trippable form (identical to the literal below); an explicit lower-precision
    // specifier such as "G15" would emit "0.3" and turn this assertion RED.
    [Fact]
    public void HighPrecisionDouble_SerializesToItsFullRoundTrippableBytes()
    {
        double highPrecision = 0.1 + 0.2; // 0.30000000000000004 — 17 significant digits.
        var schema = new StructType(new[]
        {
            new StructField("d", DataTypes.DoubleType, nullable: true, FieldMetadata.FromValues(new[]
            {
                new KeyValuePair<string, MetadataValue>("k", MetadataValue.Double(highPrecision)),
            })),
        });

        Assert.Equal(
            "{\"type\":\"struct\",\"fields\":[{\"name\":\"d\",\"type\":\"double\",\"nullable\":true," +
            "\"metadata\":{\"k\":0.30000000000000004}}]}",
            SchemaJson.ToJson(schema));

        // The exponent-formatted extremes pin that a specifier change also cannot corrupt very large/small
        // magnitudes, and that an integral-in-"G" double still keeps a fractional/exponent form so it
        // re-reads as a Double, not a Long (#330).
        Assert.Equal("{\"k\":1.7976931348623157E+308}", MetadataOnlyJson(double.MaxValue));
        Assert.Equal("{\"k\":5E-324}", MetadataOnlyJson(double.Epsilon));

        // Round-trips as a Double after the high-precision serialize (kind is preserved, value is exact).
        var parsed = (StructType)SchemaJson.FromJson(SchemaJson.ToJson(schema));
        Assert.True(parsed["d"].Metadata.TryGetValue("k", out MetadataValue? k));
        Assert.Equal(MetadataValueKind.Double, k!.Kind);
        Assert.Equal(highPrecision, k.AsDouble());
    }

    private static string MetadataOnlyJson(double value)
    {
        string json = SchemaJson.ToJson(new StructType(new[]
        {
            new StructField("d", DataTypes.DoubleType, nullable: true, FieldMetadata.FromValues(new[]
            {
                new KeyValuePair<string, MetadataValue>("k", MetadataValue.Double(value)),
            })),
        }));

        int open = json.IndexOf("{\"k\":", StringComparison.Ordinal);
        return json.Substring(open, json.IndexOf('}', open) - open + 1);
    }

    // #711: the write side must refuse to serialize a schema nested deeper than FromJson can re-read, so a
    // schema can never commit to metaData.schemaString and then be permanently unreadable. FromJson parses
    // with JsonDocumentOptions.MaxDepth = 64: a 64-deep type tree round-trips, a 65-deep one is rejected on
    // BOTH sides — the write side fails closed at ToJson rather than emitting bytes only the write side can
    // produce. The two bounds are one shared constant so they cannot drift apart again.
    [Fact]
    public void DeeplyNestedSchema_AtTheReadCap_RoundTrips_ButOneDeeperFailsClosedOnWrite()
    {
        // At the cap: writes AND reads.
        DataType atCap = NestedArrays(64);
        string json = SchemaJson.ToJson(atCap);
        Assert.Equal(atCap, SchemaJson.FromJson(json));

        // One level deeper: the write door refuses it (fail-closed), so it can never reach a schemaString.
        DataType overCap = NestedArrays(65);
        SchemaValidationException ex = Assert.Throws<SchemaValidationException>(() => SchemaJson.ToJson(overCap));
        Assert.Contains("maximum supported depth of 64", ex.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void ReadCap_And_WriteCap_AgreeExactly_SoNeitherCanDriftPastTheOther()
    {
        // Independently prove the two bounds meet at the same level: build the 65-deep JSON as raw text (so
        // the read path is exercised even though the write path now refuses to emit it) and confirm FromJson
        // rejects EXACTLY what ToJson refuses to write.
        var deep = new StringBuilder();
        for (int i = 0; i < 65; i++)
        {
            deep.Append("{\"type\":\"array\",\"elementType\":");
        }

        deep.Append("\"string\"");
        for (int i = 0; i < 65; i++)
        {
            deep.Append(",\"containsNull\":true}");
        }

        Assert.Throws<SchemaValidationException>(() => SchemaJson.FromJson(deep.ToString()));
    }

    private static DataType NestedArrays(int depth)
    {
        DataType type = DataTypes.StringType;
        for (int i = 0; i < depth; i++)
        {
            type = DataTypes.CreateArrayType(type, containsNull: true);
        }

        return type;
    }

    // #710: invalid UTF-16 (an unpaired surrogate) in a field name / metadata key / metadata string value is
    // rejected at the WRITE door. Utf8JsonWriter would otherwise transcode it to U+FFFD — a lossy,
    // non-round-tripping write. Failing closed at ToJson keeps "anything we agree to persist, we can read
    // back", and the message carries only the sanitized ROLE, never the raw (invalid) content.
    //
    // The invalid strings are built from char codes at RUNTIME (not [InlineData]): xUnit serializes theory
    // arguments for discovery, and a lone surrogate does not survive that round trip intact.
    [Fact]
    public void FieldNameWithInvalidUtf16_IsRejectedOnWrite()
    {
        var invalidNames = new[]
        {
            "x" + (char)0xD800,          // trailing lone high surrogate
            "x" + (char)0xDC00,          // trailing lone low surrogate
            (char)0xD800 + "x",          // high surrogate not followed by a low surrogate
            (char)0xDFFF + "y",          // leading lone low surrogate
            "a" + (char)0xD800 + "b",    // lone high surrogate mid-string
        };

        foreach (string invalidName in invalidNames)
        {
            var schema = new StructType(new[]
            {
                new StructField(invalidName, DataTypes.StringType, nullable: true),
            });

            SchemaValidationException ex = Assert.Throws<SchemaValidationException>(() => SchemaJson.ToJson(schema));
            Assert.Contains("field name", ex.Message, StringComparison.Ordinal);
            Assert.Contains("invalid UTF-16", ex.Message, StringComparison.Ordinal);
            // The message must never echo the invalid content itself.
            Assert.DoesNotContain('\uFFFD', ex.Message);
            Assert.DoesNotContain('\uD800', ex.Message);
        }
    }

    [Fact]
    public void MetadataKeyWithInvalidUtf16_IsRejectedOnWrite()
    {
        var schema = new StructType(new[]
        {
            new StructField("f", DataTypes.LongType, nullable: true, FieldMetadata.FromValues(new[]
            {
                new KeyValuePair<string, MetadataValue>("k\uD800", MetadataValue.Long(1)),
            })),
        });

        SchemaValidationException ex = Assert.Throws<SchemaValidationException>(() => SchemaJson.ToJson(schema));
        Assert.Contains("metadata key", ex.Message, StringComparison.Ordinal);
        Assert.Contains("invalid UTF-16", ex.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void MetadataStringValueWithInvalidUtf16_IsRejectedOnWrite()
    {
        var schema = new StructType(new[]
        {
            new StructField("f", DataTypes.LongType, nullable: true, FieldMetadata.FromValues(new[]
            {
                new KeyValuePair<string, MetadataValue>("k", MetadataValue.String("v\uDC00")),
            })),
        });

        SchemaValidationException ex = Assert.Throws<SchemaValidationException>(() => SchemaJson.ToJson(schema));
        Assert.Contains("metadata string value", ex.Message, StringComparison.Ordinal);
        Assert.Contains("invalid UTF-16", ex.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void TwoDistinctNamesThatWouldCollideOnUFFFD_AreBothRejected_SoNeitherCanBrickTheTable()
    {
        // The bricking case from #710: "x\uD800" and "x\uDC00" are DISTINCT legal names (StructType accepts
        // both), but both would serialize to "x\uFFFD" — the commit succeeds, then every read fails
        // duplicate-field-name detection. Rejecting each on write means the colliding schemaString can never
        // be committed in the first place.
        Assert.Throws<SchemaValidationException>(() => SchemaJson.ToJson(
            new StructType(new[] { new StructField("x\uD800", DataTypes.StringType, nullable: true) })));
        Assert.Throws<SchemaValidationException>(() => SchemaJson.ToJson(
            new StructType(new[] { new StructField("x\uDC00", DataTypes.StringType, nullable: true) })));

        // And a well-formed astral pair (a legitimate surrogate pair) still serializes fine — the guard
        // rejects ONLY unpaired surrogates, not all surrogate code units.
        string astralJson = SchemaJson.ToJson(
            new StructType(new[] { new StructField("x\uD83D\uDE00", DataTypes.StringType, nullable: true) }));
        Assert.Equal(
            new StructType(new[] { new StructField("x\uD83D\uDE00", DataTypes.StringType, nullable: true) }),
            SchemaJson.FromJson(astralJson));
    }
}
