using System;
using System.Collections.Generic;
using System.Linq;
using DeltaSharp.Types;
using Xunit;

namespace DeltaSharp.Core.Tests.Types;

/// <summary>
/// #679: property-level pins on the single consolidated schema serializer
/// (<c>DeltaSharp.Abstractions.SchemaJson</c>), which since the consolidation is the sole producer of
/// BOTH the Delta log <c>metaData.schemaString</c> and the Parquet footer schema string. Because those
/// two strings are now generated by one implementation, no differential test between them can detect a
/// serializer defect any more — so the serializer needs properties pinned against itself.
/// </summary>
/// <remarks>
/// Hosted in <c>DeltaSharp.Core.Tests</c> rather than the Storage suite deliberately: this project
/// multi-targets <c>net8.0;net10.0</c>, so these run on BOTH TFMs, whereas the Storage suite is
/// net10.0-only. The serializer emits doubles via <c>double.ToString("R")</c> and parses numbers via
/// <c>TryGetInt64</c>/<c>GetDouble</c>, all of which are runtime-version-sensitive, so net8.0 coverage
/// is worth real money here.
/// </remarks>
public sealed class SchemaJsonSerializerPropertyTests
{
    // A corpus spanning the recursion base (every atomic + decimal), every complex constructor
    // (array/map/struct), both nullability polarities, empty struct, deep nesting, and typed metadata
    // at nested depth — i.e. every arm of WriteType and WriteMetadataValue.
    public static TheoryData<string, DataType> Corpus()
    {
        var data = new TheoryData<string, DataType>();

        var atomics = new (string Name, DataType Type)[]
        {
            ("boolean", DataTypes.BooleanType),
            ("byte", DataTypes.ByteType),
            ("short", DataTypes.ShortType),
            ("integer", DataTypes.IntegerType),
            ("long", DataTypes.LongType),
            ("float", DataTypes.FloatType),
            ("double", DataTypes.DoubleType),
            ("string", DataTypes.StringType),
            ("binary", DataTypes.BinaryType),
            ("date", DataTypes.DateType),
            ("timestamp", DataTypes.TimestampType),
            ("timestamp_ntz", DataTypes.TimestampNtzType),
        };

        foreach ((string name, DataType type) in atomics)
        {
            data.Add(name, type);
        }

        // Decimal boundaries: precision/scale extremes carry the parameterized TypeName.
        data.Add("decimal-min", DataTypes.CreateDecimalType(1, 0));
        data.Add("decimal-max", DataTypes.CreateDecimalType(38, 38));
        data.Add("decimal-mixed", DataTypes.CreateDecimalType(20, 4));

        data.Add("array-nullable", DataTypes.CreateArrayType(DataTypes.StringType, containsNull: true));
        data.Add("array-non-nullable", DataTypes.CreateArrayType(DataTypes.LongType, containsNull: false));
        data.Add("map-nullable", DataTypes.CreateMapType(DataTypes.StringType, DataTypes.LongType, valueContainsNull: true));
        data.Add("map-non-nullable", DataTypes.CreateMapType(DataTypes.StringType, DataTypes.LongType, valueContainsNull: false));
        data.Add("empty-struct", StructType.Empty);

        var leaf = new StructType(new[]
        {
            new StructField("x", DataTypes.LongType, nullable: false),
            new StructField("y", DataTypes.CreateDecimalType(10, 2), nullable: true),
        });
        data.Add("struct", leaf);
        data.Add("array-of-struct", DataTypes.CreateArrayType(leaf, containsNull: true));
        data.Add("map-struct-key", DataTypes.CreateMapType(leaf, DataTypes.StringType, valueContainsNull: false));
        data.Add("map-struct-value", DataTypes.CreateMapType(DataTypes.StringType, leaf, valueContainsNull: true));

        // Depth-4 alternation of every complex constructor.
        DataType deep = DataTypes.CreateArrayType(
            DataTypes.CreateMapType(
                DataTypes.StringType,
                DataTypes.CreateArrayType(leaf, containsNull: false),
                valueContainsNull: true),
            containsNull: false);
        data.Add("deep-nest", deep);

        // Typed metadata at nested depth: numeric column-mapping ids, an integral double (must keep a
        // fractional part so it re-reads as Double, not Long), booleans, null, arrays, nested objects.
        var metadata = FieldMetadata.FromValues(new[]
        {
            new KeyValuePair<string, MetadataValue>("delta.columnMapping.id", MetadataValue.Long(9)),
            new KeyValuePair<string, MetadataValue>("m.arr", MetadataValue.Array(new[]
            {
                MetadataValue.Long(1), MetadataValue.Double(2.5), MetadataValue.Boolean(false), MetadataValue.Null,
            })),
            new KeyValuePair<string, MetadataValue>("m.bool", MetadataValue.Boolean(true)),
            new KeyValuePair<string, MetadataValue>("m.integral-double", MetadataValue.Double(4.0)),
            new KeyValuePair<string, MetadataValue>("m.nested", MetadataValue.Nested(FieldMetadata.FromValues(new[]
            {
                new KeyValuePair<string, MetadataValue>("deep", MetadataValue.String("v")),
            }))),
            new KeyValuePair<string, MetadataValue>("m.null", MetadataValue.Null),
        });
        data.Add("metadata-rich", new StructType(new[]
        {
            new StructField("mapped", DataTypes.CreateArrayType(leaf, containsNull: true), nullable: true, metadata),
        }));

        // Names needing JSON escaping, for the round-trip theories below. NOTE: those theories assert
        // idempotence and structural equality, BOTH of which are invariant under the encoder choice —
        // so this entry does NOT pin the escaped bytes. That is done explicitly by
        // JsonEscapingPolicy_IsPinned_SoTheEncoderCannotSilentlyChangePersistedBytes.
        data.Add("escaped-names", new StructType(new[]
        {
            new StructField("quote\"name", DataTypes.StringType, nullable: true),
            new StructField("back\\slash", DataTypes.StringType, nullable: true),
            new StructField("unicode-\u00e9\u4e2d", DataTypes.StringType, nullable: true),
        }));

        return data;
    }

    [Theory]
    [MemberData(nameof(Corpus))]
    public void SerializeParseSerialize_IsIdempotent(string name, DataType type)
    {
        // The core property: serializer and parser are mutually consistent, so a schemaString written
        // today re-reads to a type tree that re-serializes to identical bytes. A Delta schemaString is
        // persistent and cross-engine-visible, so a non-idempotent round trip would be retroactively
        // unfixable once committed to a log.
        string once = SchemaJson.ToJson(type);
        DataType parsed = SchemaJson.FromJson(once);
        string twice = SchemaJson.ToJson(parsed);

        Assert.Equal(once, twice);
        Assert.False(string.IsNullOrEmpty(once), $"corpus entry '{name}' serialized to nothing");
    }

    [Theory]
    [MemberData(nameof(Corpus))]
    public void ParsedTree_IsStructurallyEqualToTheOriginal(string name, DataType type)
    {
        // Idempotence alone would tolerate a serializer that discards a field on BOTH passes. Pin the
        // parsed tree against the original so information loss is caught too.
        DataType parsed = SchemaJson.FromJson(SchemaJson.ToJson(type));

        Assert.Equal(type, parsed);
        Assert.Equal(type.TypeName, parsed.TypeName);
        Assert.Equal(type.SimpleString, parsed.SimpleString);
        Assert.True(type.Equals(parsed), $"corpus entry '{name}' did not round-trip structurally");
    }

    [Fact]
    public void EveryAtomicType_SerializesToItsPinnedProtocolName()
    {
        // The Delta protocol fixes these spellings; they are not ours to change. Pinning them literally
        // is what catches a corrupted shared default arm (e.g. TypeName uppercased), which no
        // footer-vs-log comparison can see now that a single serializer feeds both.
        var expected = new (DataType Type, string Json)[]
        {
            (DataTypes.BooleanType, "\"boolean\""),
            (DataTypes.ByteType, "\"byte\""),
            (DataTypes.ShortType, "\"short\""),
            (DataTypes.IntegerType, "\"integer\""),
            (DataTypes.LongType, "\"long\""),
            (DataTypes.FloatType, "\"float\""),
            (DataTypes.DoubleType, "\"double\""),
            (DataTypes.StringType, "\"string\""),
            (DataTypes.BinaryType, "\"binary\""),
            (DataTypes.DateType, "\"date\""),
            (DataTypes.TimestampType, "\"timestamp\""),
            (DataTypes.TimestampNtzType, "\"timestamp_ntz\""),
            (DataTypes.CreateDecimalType(38, 18), "\"decimal(38,18)\""),
            (DataTypes.CreateDecimalType(1, 0), "\"decimal(1,0)\""),
        };

        foreach ((DataType type, string json) in expected)
        {
            Assert.Equal(json, SchemaJson.ToJson(type));
        }
    }

    [Fact]
    public void ComplexTypes_SerializeToTheirPinnedProtocolShape()
    {
        // Field ORDER inside array/map/struct objects is part of the pinned wire shape, so a reordering
        // regression (e.g. emitting containsNull before elementType) fails here.
        Assert.Equal(
            "{\"type\":\"array\",\"elementType\":\"string\",\"containsNull\":true}",
            SchemaJson.ToJson(DataTypes.CreateArrayType(DataTypes.StringType, containsNull: true)));

        Assert.Equal(
            "{\"type\":\"map\",\"keyType\":\"string\",\"valueType\":\"long\",\"valueContainsNull\":false}",
            SchemaJson.ToJson(DataTypes.CreateMapType(DataTypes.StringType, DataTypes.LongType, valueContainsNull: false)));

        Assert.Equal(
            "{\"type\":\"struct\",\"fields\":[]}",
            SchemaJson.ToJson(StructType.Empty));

        Assert.Equal(
            "{\"type\":\"struct\",\"fields\":[{\"name\":\"f\",\"type\":\"long\",\"nullable\":true,\"metadata\":{}}]}",
            SchemaJson.ToJson(new StructType(new[] { new StructField("f", DataTypes.LongType, nullable: true) })));
    }

    [Fact]
    public void JsonEscapingPolicy_IsPinned_SoTheEncoderCannotSilentlyChangePersistedBytes()
    {
        // The Utf8JsonWriter's JavaScriptEncoder is part of the persisted wire format, not an
        // implementation detail: switching to JavaScriptEncoder.UnsafeRelaxedJsonEscaping emits the SAME
        // logical schema with DIFFERENT bytes for any non-ASCII or quoted field name, changing the
        // on-disk metaData.schemaString of a committed table. Nothing else in the suite pins it —
        // round-trip idempotence and structural equality are both invariant under encoder choice — so
        // these literals are the only thing standing between a one-word constructor change and a silent
        // change to every schemaString carrying a non-ASCII column name.
        //
        // Default (strict) encoder policy, pinned exactly: non-ASCII escapes to \uXXXX with UPPERCASE
        // hex, and a double quote escapes to \u0022 rather than \". UnsafeRelaxedJsonEscaping emits the
        // literal UTF-8 character and \" respectively, so each assertion below fails under it.
        Assert.Equal(
            "{\"type\":\"struct\",\"fields\":[{\"name\":\"caf\\u00E9\",\"type\":\"string\"" +
            ",\"nullable\":true,\"metadata\":{}}]}",
            SchemaJson.ToJson(new StructType(new[]
            {
                new StructField("caf\u00e9", DataTypes.StringType, nullable: true),
            })));

        // A non-BMP-adjacent CJK code point, to pin that the escape is per-code-point uppercase hex.
        Assert.Equal(
            "{\"type\":\"struct\",\"fields\":[{\"name\":\"a\\u4E2Db\",\"type\":\"string\"" +
            ",\"nullable\":true,\"metadata\":{}}]}",
            SchemaJson.ToJson(new StructType(new[]
            {
                new StructField("a\u4e2db", DataTypes.StringType, nullable: true),
            })));

        // The quote case discriminates the two encoders most sharply: \u0022 (strict) vs \" (relaxed).
        Assert.Equal(
            "{\"type\":\"struct\",\"fields\":[{\"name\":\"q\\u0022z\",\"type\":\"string\"" +
            ",\"nullable\":true,\"metadata\":{}}]}",
            SchemaJson.ToJson(new StructType(new[]
            {
                new StructField("q\"z", DataTypes.StringType, nullable: true),
            })));

        // Metadata KEYS and string VALUES go through the same encoder, so pin them too — column-mapping
        // physical names are attacker-adjacent free text and are exactly where a non-ASCII name lands.
        Assert.Equal(
            "{\"type\":\"struct\",\"fields\":[{\"name\":\"f\",\"type\":\"long\"" +
            ",\"nullable\":true,\"metadata\":{\"k\\u00E9y\":\"v\\u00E9l\"}}]}",
            SchemaJson.ToJson(new StructType(new[]
            {
                new StructField("f", DataTypes.LongType, nullable: true, FieldMetadata.FromValues(new[]
                {
                    new KeyValuePair<string, MetadataValue>("k\u00e9y", MetadataValue.String("v\u00e9l")),
                })),
            })));
    }

    [Fact]
    public void IntegralDouble_KeepsAFractionalPart_SoItReReadsAsDouble()
    {
        // #330 interop contract: an integral Double must not collapse to a bare integer literal, or a
        // reader re-types it as Long. Asserted on the emitted bytes AND on the re-read kind.
        var schema = new StructType(new[]
        {
            new StructField("f", DataTypes.LongType, nullable: true, FieldMetadata.FromValues(new[]
            {
                new KeyValuePair<string, MetadataValue>("d", MetadataValue.Double(5.0)),
                new KeyValuePair<string, MetadataValue>("l", MetadataValue.Long(5)),
            })),
        });

        string json = SchemaJson.ToJson(schema);
        Assert.Contains("\"d\":5.0", json, StringComparison.Ordinal);
        Assert.Contains("\"l\":5", json, StringComparison.Ordinal);

        var parsed = (StructType)SchemaJson.FromJson(json);
        FieldMetadata metadata = parsed["f"].Metadata;
        Assert.True(metadata.TryGetValue("d", out MetadataValue? d));
        Assert.True(metadata.TryGetValue("l", out MetadataValue? l));
        Assert.Equal(MetadataValueKind.Double, d!.Kind);
        Assert.Equal(MetadataValueKind.Long, l!.Kind);
    }

    [Fact]
    public void FieldMetadata_SerializesInKeySortedOrder_SoOutputIsDeterministic()
    {
        // The schemaString is diffed across commits and compared by downstream consumers, so insertion
        // order must never leak into the bytes.
        var forward = new StructType(new[]
        {
            new StructField("f", DataTypes.LongType, nullable: true, FieldMetadata.FromValues(new[]
            {
                new KeyValuePair<string, MetadataValue>("a", MetadataValue.Long(1)),
                new KeyValuePair<string, MetadataValue>("b", MetadataValue.Long(2)),
                new KeyValuePair<string, MetadataValue>("c", MetadataValue.Long(3)),
            })),
        });
        var reversed = new StructType(new[]
        {
            new StructField("f", DataTypes.LongType, nullable: true, FieldMetadata.FromValues(new[]
            {
                new KeyValuePair<string, MetadataValue>("c", MetadataValue.Long(3)),
                new KeyValuePair<string, MetadataValue>("b", MetadataValue.Long(2)),
                new KeyValuePair<string, MetadataValue>("a", MetadataValue.Long(1)),
            })),
        });

        Assert.Equal(SchemaJson.ToJson(forward), SchemaJson.ToJson(reversed));
        Assert.Contains("\"metadata\":{\"a\":1,\"b\":2,\"c\":3}", SchemaJson.ToJson(forward), StringComparison.Ordinal);
    }

    [Fact]
    public void Corpus_ProducesDistinctStringsPerShape()
    {
        // Guards the corpus itself: if a future edit made two entries collide, the theories above would
        // silently lose coverage while still passing.
        string[] serialized = Corpus()
            .Select(row => SchemaJson.ToJson((DataType)row[1]!))
            .ToArray();

        Assert.Equal(serialized.Length, serialized.Distinct(StringComparer.Ordinal).Count());
    }
}
